raw_data:
    diabetic_data: "../data/raw/diabetic_data.csv"
    mapping_data : "../data/raw/IDS_mapping.csv"

processed_data:
    train_data: "../data/processed/train.csv"
    test_data : "../data/processed/test.csv"

features_data:
    train_data: "../data/features/train_features.csv"
    test_data: "../data/features/test_features.csv"